# Generated by Django 6.0.6 on 2026-07-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HAC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owners',
            name='owner_img_field',
            field=models.ImageField(blank=True, null=True, upload_to='owner_profiles/'),
        ),
    ]
