const fs = require('fs');
const path = require('path');
const filePath = path.join(__dirname, 'src', 'utils', 'translations.js');

const newKeys = {
  en: {
    joined_property: "Joined Property",
    search_location_property: "Search location, property...",
    joined: "Joined",
    accepted: "Accepted",
    pending: "Pending",
    rejected: "Rejected",
    full: "Full",
    welcome_to: "Welcome to",
    due_today: "Due Today",
    due_soon: "Due Soon",
    overdue: "Overdue",
    upcoming: "Upcoming",
    verifying: "Verifying",
    paid: "Paid",
    upi_id: "UPI ID",
    pay_using_upi_app: "Pay using any UPI App",
    upload_payment_screenshot: "Upload Payment Screenshot",
    add_note: "Add a note...",
    no_address_available: "No Address Available",
    hostel: "Hostel",
    apartment: "Apartment",
    commercial: "Commercial",
  },
  hi: {
    joined_property: "जुड़ी हुई संपत्ति",
    search_location_property: "स्थान, संपत्ति खोजें...",
    joined: "जुड़े",
    accepted: "स्वीकृत",
    pending: "लंबित",
    rejected: "अस्वीकृत",
    full: "भरा हुआ",
    welcome_to: "स्वागत है",
    due_today: "आज देय",
    due_soon: "जल्द देय",
    overdue: "अतिदेय",
    upcoming: "आगामी",
    verifying: "सत्यापन हो रहा है",
    paid: "भुगतान हुआ",
    upi_id: "यूपीआई आईडी",
    pay_using_upi_app: "किसी भी UPI ऐप से भुगतान करें",
    upload_payment_screenshot: "भुगतान स्क्रीनशॉट अपलोड करें",
    add_note: "नोट जोड़ें...",
    no_address_available: "कोई पता उपलब्ध नहीं",
    hostel: "हॉस्टल",
    apartment: "अपार्टमेंट",
    commercial: "व्यावसायिक",
  },
  te: {
    joined_property: "చేరిన ఆస్తి",
    search_location_property: "స్థలం, ఆస్తి వెతకండి...",
    joined: "చేరారు",
    accepted: "అంగీకరించారు",
    pending: "పెండింగ్",
    rejected: "తిరస్కరించారు",
    full: "నిండిపోయింది",
    welcome_to: "స్వాగతం",
    due_today: "ఈరోజు చెల్లించాలి",
    due_soon: "త్వరలో చెల్లించాలి",
    overdue: "గడువు మించింది",
    upcoming: "రానున్నది",
    verifying: "ధృవీకరిస్తున్నారు",
    paid: "చెల్లించారు",
    upi_id: "యూపీఐ ఐడీ",
    pay_using_upi_app: "ఏదైనా UPI యాప్ ద్వారా చెల్లించండి",
    upload_payment_screenshot: "చెల్లింపు స్క్రీన్‌షాట్ అప్‌లోడ్ చేయండి",
    add_note: "నోట్ జోడించండి...",
    no_address_available: "చిరునామా అందుబాటులో లేదు",
    hostel: "హాస్టల్",
    apartment: "అపార్ట్‌మెంట్",
    commercial: "వ్యాపార",
  },
  ta: {
    joined_property: "இணைந்த சொத்து",
    search_location_property: "இடம், சொத்து தேடுங்கள்...",
    joined: "சேர்ந்தவர்",
    accepted: "ஏற்றுக்கொள்ளப்பட்டது",
    pending: "நிலுவையில்",
    rejected: "நிராகரிக்கப்பட்டது",
    full: "நிரம்பியது",
    welcome_to: "வரவேற்கிறோம்",
    due_today: "இன்று செலுத்த வேண்டும்",
    due_soon: "விரைவில் செலுத்த வேண்டும்",
    overdue: "தாமதமான",
    upcoming: "வரவிருக்கும்",
    verifying: "சரிபார்க்கிறோம்",
    paid: "செலுத்தப்பட்டது",
    upi_id: "யுபிஐ ஐடி",
    pay_using_upi_app: "எந்த UPI ஆப்பிலும் செலுத்துங்கள்",
    upload_payment_screenshot: "கட்டண ஸ்கிரீன்ஷாட் பதிவேற்றவும்",
    add_note: "குறிப்பு சேர்க்கவும்...",
    no_address_available: "முகவரி கிடைக்கவில்லை",
    hostel: "விடுதி",
    apartment: "அடுக்குமாடி",
    commercial: "வணிக",
  },
  mr: {
    joined_property: "सामील मालमत्ता",
    search_location_property: "ठिकाण, मालमत्ता शोधा...",
    joined: "सामील",
    accepted: "स्वीकृत",
    pending: "प्रलंबित",
    rejected: "नाकारले",
    full: "भरलेले",
    welcome_to: "स्वागत आहे",
    due_today: "आज देय",
    due_soon: "लवकरच देय",
    overdue: "थकीत",
    upcoming: "येणारे",
    verifying: "सत्यापन होत आहे",
    paid: "भरले",
    upi_id: "युपीआय आयडी",
    pay_using_upi_app: "कोणत्याही UPI अ‍ॅपने भरा",
    upload_payment_screenshot: "पेमेंट स्क्रीनशॉट अपलोड करा",
    add_note: "नोंद जोडा...",
    no_address_available: "पत्ता उपलब्ध नाही",
    hostel: "वसतिगृह",
    apartment: "अपार्टमेंट",
    commercial: "व्यावसायिक",
  },
  kn: {
    joined_property: "ಸೇರಿದ ಆಸ್ತಿ",
    search_location_property: "ಸ್ಥಳ, ಆಸ್ತಿ ಹುಡುಕಿ...",
    joined: "ಸೇರಿದ್ದಾರೆ",
    accepted: "ಒಪ್ಪಿಗೆ ಆಯಿತು",
    pending: "ಬಾಕಿ ಇದೆ",
    rejected: "ತಿರಸ್ಕರಿಸಲಾಗಿದೆ",
    full: "ತುಂಬಿಹೋಗಿದೆ",
    welcome_to: "ಸ್ವಾಗತ",
    due_today: "ಇಂದು ಪಾವತಿ ಮಾಡಬೇಕು",
    due_soon: "ಶೀಘ್ರದಲ್ಲಿ ಪಾವತಿ ಮಾಡಬೇಕು",
    overdue: "ಅವಧಿ ಮೀರಿದೆ",
    upcoming: "ಮುಂಬರುವ",
    verifying: "ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ",
    paid: "ಪಾವತಿ ಆಗಿದೆ",
    upi_id: "ಯುಪಿಐ ಐಡಿ",
    pay_using_upi_app: "ಯಾವುದೇ UPI ಅಪ್ ಮೂಲಕ ಪಾವತಿ ಮಾಡಿ",
    upload_payment_screenshot: "ಪಾವತಿ ಸ್ಕ್ರೀನ್‌ಶಾಟ್ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    add_note: "ಟಿಪ್ಪಣಿ ಸೇರಿಸಿ...",
    no_address_available: "ವಿಳಾಸ ಲಭ್ಯವಿಲ್ಲ",
    hostel: "ವಸತಿ ಗೃಹ",
    apartment: "ಅಪಾರ್ಟ್‌ಮೆಂಟ್",
    commercial: "ವಾಣಿಜ್ಯ",
  },
  ml: {
    joined_property: "ചേർന്ന സ്വത്ത്",
    search_location_property: "സ്ഥലം, സ്വത്ത് തിരയുക...",
    joined: "ചേർന്നു",
    accepted: "അംഗീകരിച്ചു",
    pending: "തീർപ്പുകൽപ്പിക്കാത്ത",
    rejected: "നിരസിച്ചു",
    full: "നിറഞ്ഞു",
    welcome_to: "സ്വാഗതം",
    due_today: "ഇന്ന് അടക്കണം",
    due_soon: "ഉടൻ അടക്കണം",
    overdue: "കാലഹരണപ്പെട്ടത്",
    upcoming: "വരാനിരിക്കുന്നത്",
    verifying: "പരിശോധിക്കുന്നു",
    paid: "അടച്ചു",
    upi_id: "യുപിഐ ഐഡി",
    pay_using_upi_app: "ഏത് UPI ആപ്പ് ഉപയോഗിച്ചും അടയ്ക്കുക",
    upload_payment_screenshot: "പേയ്‌മെന്റ് സ്ക്രീൻഷോട്ട് അപ്‌ലോഡ് ചെയ്യുക",
    add_note: "കുറിപ്പ് ചേർക്കുക...",
    no_address_available: "വിലാസം ലഭ്യമല്ല",
    hostel: "ഹോസ്റ്റൽ",
    apartment: "അപ്പാർട്ട്‌മെന്റ്",
    commercial: "വാണിജ്യ",
  },
  gu: {
    joined_property: "જોડાયેલ મિલકત",
    search_location_property: "સ્થળ, મિલકત શોધો...",
    joined: "જોડાયા",
    accepted: "સ્વીકૃત",
    pending: "બાકી",
    rejected: "નકારી",
    full: "ભરાઈ ગઈ",
    welcome_to: "સ્વાગત છે",
    due_today: "આજે ભરો",
    due_soon: "ટૂંક સમયમાં ભરો",
    overdue: "બાકી",
    upcoming: "આગામી",
    verifying: "ચકાસાઈ રહ્યું છે",
    paid: "ભરાઈ ગઈ",
    upi_id: "યુપીઆઈ આઈડી",
    pay_using_upi_app: "કોઈ પણ UPI એપ દ્વારા ચૂકવો",
    upload_payment_screenshot: "ચૂકવણી સ્ક્રીનશૉટ અપલોડ કરો",
    add_note: "નોંધ ઉમેરો...",
    no_address_available: "સરનામું ઉપલબ્ધ નથી",
    hostel: "હૉસ્ટેલ",
    apartment: "એપાર્ટમેન્ટ",
    commercial: "વ્યવસાયિક",
  },
  pa: {
    joined_property: "ਜੁੜੀ ਜਾਇਦਾਦ",
    search_location_property: "ਥਾਂ, ਜਾਇਦਾਦ ਖੋਜੋ...",
    joined: "ਜੁੜੇ",
    accepted: "ਮਨਜ਼ੂਰ",
    pending: "ਬਕਾਇਆ",
    rejected: "ਰੱਦ",
    full: "ਭਰਿਆ",
    welcome_to: "ਜੀ ਆਇਆਂ",
    due_today: "ਅੱਜ ਅਦਾ ਕਰੋ",
    due_soon: "ਜਲਦੀ ਅਦਾ ਕਰੋ",
    overdue: "ਮਿਆਦ ਲੰਘ ਗਈ",
    upcoming: "ਆਉਣ ਵਾਲਾ",
    verifying: "ਪੁਸ਼ਟੀ ਹੋ ਰਹੀ ਹੈ",
    paid: "ਅਦਾ ਕੀਤਾ",
    upi_id: "ਯੂਪੀਆਈ ਆਈਡੀ",
    pay_using_upi_app: "ਕਿਸੇ ਵੀ UPI ਐਪ ਨਾਲ ਅਦਾ ਕਰੋ",
    upload_payment_screenshot: "ਭੁਗਤਾਨ ਸਕ੍ਰੀਨਸ਼ਾਟ ਅਪਲੋਡ ਕਰੋ",
    add_note: "ਨੋਟ ਜੋੜੋ...",
    no_address_available: "ਪਤਾ ਉਪਲਬਧ ਨਹੀਂ",
    hostel: "ਹੋਸਟਲ",
    apartment: "ਅਪਾਰਟਮੈਂਟ",
    commercial: "ਵਪਾਰਕ",
  },
  bn: {
    joined_property: "যোগ দেওয়া সম্পত্তি",
    search_location_property: "অবস্থান, সম্পত্তি খুঁজুন...",
    joined: "যোগ দিয়েছেন",
    accepted: "গৃহীত",
    pending: "মুলতুবি",
    rejected: "প্রত্যাখ্যাত",
    full: "পূর্ণ",
    welcome_to: "স্বাগতম",
    due_today: "আজ দিন",
    due_soon: "শীঘ্রই দিন",
    overdue: "মেয়াদ পেরিয়েছে",
    upcoming: "আসন্ন",
    verifying: "যাচাই হচ্ছে",
    paid: "পরিশোধিত",
    upi_id: "ইউপিআই আইডি",
    pay_using_upi_app: "যেকোনো UPI অ্যাপে পরিশোধ করুন",
    upload_payment_screenshot: "পেমেন্ট স্ক্রিনশট আপলোড করুন",
    add_note: "নোট যোগ করুন...",
    no_address_available: "ঠিকানা পাওয়া যায়নি",
    hostel: "হোস্টেল",
    apartment: "অ্যাপার্টমেন্ট",
    commercial: "বাণিজ্যিক",
  },
  or: {
    joined_property: "ଯୋଗ ଦେଇଥିବା ସମ୍ପତ୍ତି",
    search_location_property: "ଅବସ୍ଥାନ, ସମ୍ପତ୍ତି ଖୋଜନ୍ତୁ...",
    joined: "ଯୋଗ ଦେଇଛନ୍ତି",
    accepted: "ଗ୍ରହଣ ହୋଇଛି",
    pending: "ମୁଲ୍ତୁବି",
    rejected: "ପ୍ରତ୍ୟାଖ୍ୟାତ",
    full: "ପୂର୍ଣ୍ଣ",
    welcome_to: "ସ୍ୱାଗତ",
    due_today: "ଆଜି ଦେୟ",
    due_soon: "ଶୀଘ୍ର ଦେୟ",
    overdue: "ଅବଧି ଅତିକ୍ରାନ୍ତ",
    upcoming: "ଆସନ୍ତା",
    verifying: "ଯାଞ୍ଚ ହଉଛି",
    paid: "ଦାଖଲ ହୋଇଛି",
    upi_id: "ୟୁପିଆଇ ଆଇଡି",
    pay_using_upi_app: "ଯେକୌଣସି UPI ଆପ ଦ୍ୱାରା ଦୁଆ ଦିଅନ୍ତୁ",
    upload_payment_screenshot: "ଦଉଡ ସ୍କ୍ରିନଶଟ ଅପଲୋଡ କରନ୍ତୁ",
    add_note: "ଟିକେ ଯୋଡ଼ନ୍ତୁ...",
    no_address_available: "ଠିକଣା ଉପଲବ୍ଧ ନୁହେଁ",
    hostel: "ହୋଷ୍ଟେଲ",
    apartment: "ଅ‌ପାର୍ଟ‌ମେଣ୍ଟ",
    commercial: "ବ୍ୟବସାୟିକ",
  }
};

let content = fs.readFileSync(filePath, 'utf8');

for (const [lang, keys] of Object.entries(newKeys)) {
  const injected = Object.entries(keys).map(([k, v]) => `    ${k}: "${v}",`).join('\n');
  // Match: `en: {` or `te: {` etc at the start of language block
  const regex = new RegExp(`(\\b${lang}\\s*:\\s*\\{)`, 'g');
  content = content.replace(regex, `$1\n${injected}`);
}

fs.writeFileSync(filePath, content, 'utf8');
console.log("✅ All missing translation keys injected successfully!");
